<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="EPBYGROW0336" name="PikabuTest" tests="10" failures="1" timestamp="20 Apr 2017 08:59:29 GMT" time="118.169" errors="0">
  <testcase name="loginWithGoogleAccount" time="14.871" classname="PikabuTest"/>
  <testcase name="postHideTest" time="11.882" classname="PikabuTest"/>
  <testcase name="verifyHotPostsPage" time="21.237" classname="PikabuTest"/>
  <testcase name="postRatingUp" time="20.898" classname="PikabuTest"/>
  <testcase name="verifyBestPostPage" time="9.882" classname="PikabuTest"/>
  <testcase name="verifyRecentPostsPage" time="23.802" classname="PikabuTest"/>
  <testcase name="addPostWithUnregUser" time="7.486" classname="PikabuTest"/>
  <testcase name="searchTest" time="8.111" classname="PikabuTest">
    <failure type="java.lang.AssertionError" message="Search test is fail! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Search test is fail! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at PikabuTest.searchTest(PikabuTest.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- searchTest -->
  <testcase name="loginTest" classname="PikabuTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" classname="PikabuTest">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- PikabuTest -->
